#!/usr/bin/env bash
#
# bootstrap.sh — One-step setup for github-sync on a new machine.
#
# What it does:
#   1. Checks prerequisites (git, gh, jq)
#   2. Verifies GitHub CLI authentication
#   3. Installs github-sync to ~/.local/bin
#   4. Writes config from your git global identity
#   5. Installs a background service (launchd on macOS, systemd on Linux)
#   6. Runs the first sync immediately
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/Zynapses/github-sync/main/bootstrap.sh | bash
#   # — or —
#   git clone https://github.com/Zynapses/github-sync.git && cd github-sync && ./bootstrap.sh

set -euo pipefail

REPO_URL="https://github.com/Zynapses/github-sync.git"
INSTALL_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config/github-sync"
DATA_DIR="$HOME/.local/share/github-sync"
SYNC_INTERVAL=300  # 5 minutes

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}ℹ${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC} $*"; }
fail()    { echo -e "${RED}✗${NC} $*"; exit 1; }

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║        github-sync — One-Step Bootstrap         ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# ─── 1. Check prerequisites ──────────────────────────────────────────────────
info "Checking prerequisites..."
missing=false

for cmd in git jq; do
    if command -v "$cmd" &>/dev/null; then
        success "$cmd found"
    else
        echo -e "${RED}✗${NC} $cmd not found"
        missing=true
    fi
done

if command -v gh &>/dev/null; then
    success "gh found ($(gh --version | head -1))"
else
    echo -e "${RED}✗${NC} gh (GitHub CLI) not found"
    missing=true
fi

if [[ "$missing" == "true" ]]; then
    echo ""
    echo "Install missing tools:"
    if [[ "$(uname)" == "Darwin" ]]; then
        echo "  brew install gh jq"
    else
        echo "  sudo apt install gh jq   # Debian/Ubuntu"
        echo "  sudo dnf install gh jq   # Fedora"
    fi
    fail "Please install missing dependencies and re-run."
fi

# ─── 2. Check GitHub auth ────────────────────────────────────────────────────
echo ""
info "Checking GitHub authentication..."
if gh auth status &>/dev/null; then
    GH_USER="$(gh api user --jq '.login' 2>/dev/null || echo "unknown")"
    success "Authenticated as: $GH_USER"
else
    fail "Not authenticated. Run 'gh auth login' first, then re-run this script."
fi

# ─── 3. Get or clone the repo ────────────────────────────────────────────────
echo ""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"

# Check if we're already inside the cloned repo
if [[ -f "$SCRIPT_DIR/github-sync.sh" ]]; then
    REPO_DIR="$SCRIPT_DIR"
    success "Using local repo: $REPO_DIR"
else
    REPO_DIR="$(mktemp -d)"
    info "Cloning github-sync..."
    git clone --quiet "$REPO_URL" "$REPO_DIR"
    success "Cloned to temporary directory"
    CLEANUP_REPO=true
fi

# ─── 4. Install to ~/.local/bin ───────────────────────────────────────────────
echo ""
info "Installing github-sync..."
mkdir -p "$INSTALL_DIR"
cp "$REPO_DIR/github-sync.sh" "$INSTALL_DIR/github-sync"
chmod +x "$INSTALL_DIR/github-sync"
success "Installed to $INSTALL_DIR/github-sync"

# Ensure ~/.local/bin is in PATH
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$INSTALL_DIR"; then
    warn "$INSTALL_DIR is not in your PATH."

    SHELL_RC=""
    if [[ -f "$HOME/.zshrc" ]]; then
        SHELL_RC="$HOME/.zshrc"
    elif [[ -f "$HOME/.bashrc" ]]; then
        SHELL_RC="$HOME/.bashrc"
    fi

    if [[ -n "$SHELL_RC" ]]; then
        echo "export PATH=\"$INSTALL_DIR:\$PATH\"" >> "$SHELL_RC"
        export PATH="$INSTALL_DIR:$PATH"
        success "Added $INSTALL_DIR to PATH in $SHELL_RC"
    else
        warn "Add this to your shell profile: export PATH=\"$INSTALL_DIR:\$PATH\""
    fi
fi

# ─── 5. Write config ─────────────────────────────────────────────────────────
echo ""
info "Writing config..."
mkdir -p "$CONFIG_DIR" "$DATA_DIR"

GIT_NAME="$(git config --global user.name 2>/dev/null || echo "")"
GIT_EMAIL="$(git config --global user.email 2>/dev/null || echo "")"

if [[ -z "$GIT_NAME" || -z "$GIT_EMAIL" ]]; then
    fail "Git global user.name or user.email not set. Run:
  git config --global user.name \"Your Name\"
  git config --global user.email \"you@example.com\"
Then re-run this script."
fi

cat > "$CONFIG_DIR/config" <<EOF
# github-sync configuration
# Generated by: bootstrap.sh
# Date: $(date '+%Y-%m-%d %H:%M:%S')
# Machine: $(hostname)

GITHUB_SYNC_DIR="\$HOME/Projects"
GITHUB_SYNC_GIT_NAME="$GIT_NAME"
GITHUB_SYNC_GIT_EMAIL="$GIT_EMAIL"
GITHUB_SYNC_PROTOCOL="https"
GITHUB_SYNC_FORKS="false"
GITHUB_SYNC_ARCHIVED="false"
EOF

success "Config: $CONFIG_DIR/config"
success "Identity: $GIT_NAME <$GIT_EMAIL>"

# ─── 6. Install background service ───────────────────────────────────────────
echo ""
info "Installing background service (every ${SYNC_INTERVAL}s)..."

if [[ "$(uname)" == "Darwin" ]]; then
    # macOS — launchd
    PLIST_DIR="$HOME/Library/LaunchAgents"
    PLIST_FILE="$PLIST_DIR/com.github-sync.agent.plist"
    mkdir -p "$PLIST_DIR"

    cat > "$PLIST_FILE" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.github-sync.agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>${INSTALL_DIR}/github-sync</string>
    </array>
    <key>StartInterval</key>
    <integer>${SYNC_INTERVAL}</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${DATA_DIR}/launchd-stdout.log</string>
    <key>StandardErrorPath</key>
    <string>${DATA_DIR}/launchd-stderr.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${INSTALL_DIR}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
PLIST

    launchctl unload "$PLIST_FILE" 2>/dev/null || true
    launchctl load "$PLIST_FILE"
    success "launchd agent installed: syncing every ${SYNC_INTERVAL}s, starts at login"

elif [[ "$(uname)" == "Linux" ]]; then
    # Linux — systemd
    UNIT_DIR="$HOME/.config/systemd/user"
    mkdir -p "$UNIT_DIR"

    cat > "$UNIT_DIR/github-sync.service" <<SVC
[Unit]
Description=GitHub Sync
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${INSTALL_DIR}/github-sync
Environment=PATH=${INSTALL_DIR}:/usr/local/bin:/usr/bin:/bin

[Install]
WantedBy=default.target
SVC

    cat > "$UNIT_DIR/github-sync.timer" <<TMR
[Unit]
Description=Run GitHub Sync periodically

[Timer]
OnBootSec=60
OnUnitActiveSec=${SYNC_INTERVAL}s
Persistent=true

[Install]
WantedBy=timers.target
TMR

    systemctl --user daemon-reload
    systemctl --user enable --now github-sync.timer
    success "systemd timer installed: syncing every ${SYNC_INTERVAL}s"
else
    warn "Unknown OS — skipping background service. Use: github-sync --loop $SYNC_INTERVAL"
fi

# ─── 7. Run first sync ───────────────────────────────────────────────────────
echo ""
info "Running first sync..."
echo ""
"$INSTALL_DIR/github-sync"

# ─── Cleanup ──────────────────────────────────────────────────────────────────
if [[ "${CLEANUP_REPO:-false}" == "true" ]]; then
    rm -rf "$REPO_DIR"
fi

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║            ✓ Bootstrap Complete!                ║"
echo "╠══════════════════════════════════════════════════╣"
echo "║  Repos synced to:  ~/Projects                   ║"
echo "║  Syncing every:    5 minutes (background)       ║"
echo "║  Manual sync:      github-sync                  ║"
echo "║  Check status:     github-sync --status         ║"
echo "║  View logs:        cat ~/.local/share/           ║"
echo "║                    github-sync/sync.log          ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
